### ISSUE TITLE
支持关键字过滤

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#10]
以前好基友 @billgateshxk 做的萌电波程序，在他的mac机上看了演示，凡是遇到OST或者サントラ之类的关键字会自动屏蔽，屏蔽掉了纯音乐，然后剩下来的都是歌曲（当然东方之类的mad和电视游戏OST之类好多都屏蔽不掉），就感觉这个关键字过滤器功能好贴心，啥时候也想重现一个。

**Comment by 3usi9** [comment]
Okay... That’s easy

**Comment by mike2718** [comment]
@3usi9 =w=

**Comment by 3usi9** [comment]
清闲的时间总是过得那么快啊QwQ
下一次咱再有精力维护这个项目就不知道是什么时候了...
好的，暂时放置play吧~

对了，6pixel给出一个实例(只能用mlterm...所以是terminal-specific啦)
![screenshot from 2017-09-20 10-55-30](https://user-images.githubusercontent.com/20506941/30626022-beea7088-9df9-11e7-919b-2a079efdcf3b.png)

github项目：libsixel
