### ISSUE TITLE
支持显示专辑封面

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#11]
这个想法一开始就有，但是怎么也想不出在命令行界面能显示的工具（不用从源代码重新写程序，而是直接用bash控制已有的命令行工具）。直到某一天在横滨的图书馆看到一本Linux之类的书籍（名字忘了）不经意间提到了个display的程序，可以预览图片，一查居然是大名鼎鼎ImageMagick的一部分？然后就把这货丢进了脚本循环，还真能显示专辑图片了，然而目测它运行之后自己不会exit，得手动kill掉？得想法让每首歌曲播完之后或者切换新歌曲之后立即换成新的图片。另外这货只是在终端之外运行，也就是说除了终端之外必须得有图形界面，我一开始开发的初衷是那种完全服务器的环境下。。。

**Comment by 3usi9** [comment]
咱也是学生党啊QwQ, 而且仓促写的代码和文档还需要维护…[当然，如果是调用外部程序实现还是很简单的…只是大概脑补了一下…感觉效果不会太好]

**Comment by mike2718** [comment]
好吧总之很感谢，辛苦了（摸摸

**Comment by 3usi9** [comment]
额…我大概了解了一些…显示图片是terminal-specific的...比如mac就能比较方便的实现，或者一些terminal支持6pixel…但是这样既没有通用性也不方便写…于是我决定直接做一个无边框的外部程序hover到terminal上…

**Comment by 3usi9** [comment]
呃...为啥我这里一获取图像就是502...虽然fq之后能get到...还是很不爽....
大概思路我写好了...你可以自己修改一下...我是没办法调整了...throw了error我都不知道是client还是server的问题....

**Comment by 3usi9** [comment]
哦对了，如果想在tty里看图，试一下fbi(sudo apt-get install fbi), 不会令人失望的

**Comment by mike2718** [comment]
@3usi9 感觉这货越来越强大了。。。虽然现在已经很强大（
