### ISSUE TITLE
支持执行后立即播放歌曲

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#13]
其实原来开发的初衷是那种完全服务器的环境下，只有音箱，然后一开脚本立即就能听歌曲的，就有点类似一打开收音机就有电台的声音那种感觉，开着电台就一直有声音，除非收音机没电或者世界末日（泥垢。觉得后来无论增加啥屠龙功能，这个也要有。。。执行后立即播放，就有点类似苹果的交互设计那种感觉。（虽然人人点赞的那本苹果砖头书没读过。。。

**Comment by 3usi9** [comment]
哦哦，如果是一直播放(不停止)的功能我会添加的...

**Comment by mike2718** [comment]
@3usi9 回头试试看。。。假设本地的音乐如果是空的情况下，也会有播放歌曲么？比如我是个小白，执行了脚本之后会有啥回应

**Comment by 3usi9** [comment]
它会输出There is no music然后退出

**Comment by 3usi9** [comment]
好吧...提示几个我这几天使用的功能
加入-D功能并在UI上显示SONG_ID的目的：如果听到一首喜欢的歌曲就直接新开一个tty，用moefm -D下载到数据库

加入本地数据库导出的时候，会自动把metadata写到输出的mp3里面....

加入-l 功能是因为这里网络不是很好，在线听经常断线，于是就边听边下载了..

**Comment by mike2718** [comment]
@3usi9 比如这个

```
lubuntu@lubuntu:~/moefm.sh$ ./moefm.sh 
Please enter an argument, use ./moefm.sh -h to get help
lubuntu@lubuntu:~/moefm.sh$ moefm -L -S "#"
moefm: command not found
lubuntu@lubuntu:~/moefm.sh$ ./moefm.sh -L -S "#"
There isn't any song...
lubuntu@lubuntu:~/moefm.sh$ moefm -X
moefm: command not found
lubuntu@lubuntu:~/moefm.sh$ moefm.sh -X
moefm.sh: command not found
lubuntu@lubuntu:~/moefm.sh$ ./moefm.sh -X

曲名:   採光の虹～Holy-Rainbow～
专辑:   秋葉文化祭コンピレーションCD Vol.2
艺术家: 未知
歌曲ID: 56215

[SPACE] 暂停/继续 [q] 下一曲 [Ctrl-Z] 退出

[1]+  Stopped                 ./moefm.sh -X
lubuntu@lubuntu:~/moefm.sh$ 

```
比方说，虽然那确实没有歌曲，但是启动以后不显示There isn't any song...，
而是直接播放了，播放了的歌曲也自动在后台写入了数据库，用户觉得自己就像在用收音机，只是在按下开关和调频而已，完全不知道收音机的原理和电磁波的原理。切换歌曲就自动后台写入数据库，退出就自动保存。
还有比方说一开始启动，提示需要重启终端，有没有办法让它后台完成，不用重启之类，就没有任何信息输出；或者虽然需要重启，但是让它直接播放了，重启让它留在下一次用户手动启动来完成。
就是一执行脚本就直接在后台做完了所有的事情，包括新建数据库文件保存退出啥的。
当然last.fm之类必须要用户名和密码，比方说可以让它用选项或者手写配置文件来设置，一开始运行就不需要设置last.fm，而是直接开始播放音乐。

**Comment by 3usi9** [comment]
@mike2718 
额…虽然个人觉得加一个-X参数没有那么难…好吧，那就把这个写到默认选项里

那个重启终端的求改进…那段代码本来是输入路径后新建一个环境变量$MOEFM_DATABASE  ，然后使用这个环境变量的，
```bash
echo "MOEFM_DATABASE=$your_input" >> "$HOME/.bashrc"
source "$HOME/.bashrc"
```

但是这里咱调试的时候总是没办法刷新bashrc，最后是没选择了才新开一个terminal(打开的时候会自动加载.bashrc文件，这样就读取到刚刚写入的数据了)
这其实是一个bug…求修复…


last.fm如果什么都不设置也可以正常使用moefm.s h的其他功能，加入-U参数并不会同步到last.fm，个人觉得设不设置都无所谓…当然其实是咱比较懒才没有写到选项里

其实wget也有断点续传功能[wget -c]，这个咱也知道，但是server好像不吃这一套…,断点续传⇔速度为零(也有可能是这里网络不好)，所以并没有下载选项都没有加-c…

其实咱的设计思维更像*nix的模式…不过这儿咱也学习到了这样一种简化用户接口的思想
