### ISSUE TITLE
支持从日本亚马逊下载专辑封面

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#14]
比如一首歌曲，当它不存在任何封面的时候，或者检测到封面图片质量太差，就去日本亚马逊或者类似的blabla网站下载尺寸稍微大一点的图片（该功能可以在选项中关闭）。目测这货需要正则来爬网页数据。。。当年写过一个PHP正则爬虫来爬了好多日中辞典（怀念，虽然现在已经忘了写法）。以前看到有个日本人做的itunes辅助程序做到了这个。。。当然名字忘了。反正也没抱太大希望，就先挂在这吧，反正是命令行程序，图形功能也不用太强。。。吧

**Comment by 3usi9** [comment]
现在连显示都成问题啊喂(逃
