### ISSUE TITLE
支持听过的歌曲自动同步到推特

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#15]
小伙伴们喜闻乐见的功能，听过的歌曲同步上推，加标签#nowplaying，实现的软件有なうぷれ等等。。。
还支持自定义tweet文模板。。。
自动检测网络状态，当断网时或者post不上去时，自动保存本地数据库；当网络状态良好时，后台积累到一定数量（比如2~10首）自动发推。同时，在网络状态良好时，把之前post失败的歌曲自动发推。

目测需要post间隔。。。

目测调试需要VPN。。。

哇塞，这已经不是脚本的等级了，流弊啊.

**Comment by 3usi9** [comment]
@mike2718
是啊…这已经不是脚本了…以后重构代码的时候加入这个功能吧

**Comment by 3usi9** [comment]
现在加的坑越多，以后重写的时候就越痛苦…
