### ISSUE TITLE
支持显示歌词

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#18]
也是なうぷれ的功能。

最低限做到下载歌词不显示。
第二步显示完整歌词。
第三步同步显示歌词。（目测无法实现。。。）

也不知道なうぷれ是从哪个源获取到歌词的，真准确。。。

**Comment by 3usi9** [comment]
应该是自己建的服务器吧...也就是说需要手工整理歌词数据...

**Comment by mike2718** [comment]
@3usi9 感谢推送。还有不知道你要不要这个项目，最近开始忙就活，如果成功的话估计将来一段时间也没时间merge了，将来也不会有机会再写代码，也算是梦想破灭吧。如果你需要这个项目的话，我可以在后台设置里把整个项目移交给你。比起我莫名其妙afk，至少还有人管理这个项目。。。

**Comment by 3usi9** [comment]
@mike2718
虽然咱平常也不是很有时间，但是还没有可怕到没机会写代码😱，如果你实在抽不出空，我倒是可以帮忙管理一下这个项目，不过转项目就没必要了…等天时地利人和准备重构的时候再说吧

**Comment by mike2718** [comment]
@3usi9 好吧，那就拜托了。
