### ISSUE TITLE
支持同步歌曲到last.fm

### ISSUE THREAD

**Issue by mike2718** [mike2718/moefm.sh#8]
RT

**Comment by 3usi9** [comment]
...所以...看了API文档后...其实想问一下关于Scrobbler...(原谅我曾经并未使用过last.fm)
1. 如果某首歌在last.fm数据库里没有...可以发布scrobble嘛?
(比如冷门歌曲, 或者metadata不完整的歌曲)
2. 如果可以，发布后如何听到这首歌？(上传音乐文件到last.fm的数据库？)
3. mail...list...or....gitter........Github doesn't have chat function.........

**Comment by mike2718** [comment]
@3usi9 last.fm就是记录歌曲信息，包括专辑名，艺术家名和歌曲名啥的，数据库里没有目测也能发布scrobble。只是单纯记录而已，相当于日志，目测没法听。。。最近学业比较忙没时间开发w

**Comment by 3usi9** [comment]
还是你来merge吧...话说如果有这种需求一开始为什么要用bash...

**Comment by 3usi9** [comment]
对了...我在```scrobble.py```下封装了scrobble方法...可以用bash直接调用...
比如(当然usr和passwd要提前设定好)
```bash
python3 -c 'import scrobble; scrobble.Scrobble_one("Oath Sign", "Oath Sign", "Lisa")'
```
就可以直接添加一条scrobble，可以通过调用这个命令批量导入scrobble....
如果要这样做，建议每导入一条 sleep 500ms

**Comment by mike2718** [comment]
开个moefm.py坑得了（
